name: 'Tests: node.js 10 - 20'

on: [pull_request, push]

permissions:
  contents: read

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '^16.20.2 || ^18.20.6'
      type: minors
      command: npm run tests-only

  node:
    name: 'node 10 - 20'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: true
