name: 'Tests: node.js >= 20'

on: [pull_request, push]

permissions:
  contents: read

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '^20.18.3 || ^22.14.0 || >= 23.8'
      type: minors
      command: npm run tests-only

  node:
    name: 'node >= 20'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: true
